version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: players
      POSTGRES_USER: anton
      POSTGRES_PASSWORD: pass
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge