spring:
  datasource:
    url: jdbc:postgresql://postgres_db:5432/players
    username: anton
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
app:
  token: ${TOKEN}